from ultralytics import YOLO
from pathlib import Path
import pandas as pd
import numpy as np

def save_results(results, save_path):
    '''
    Saves results object generated by detect_player_keypoints() into a csv.
    Each row is one frame. Keypoints follow the standard YOLO human pose order (17 keypoints):
      nose, left_eye, right_eye, left_ear, right_ear,
      left_shoulder, right_shoulder, left_elbow, right_elbow,
      left_wrist, right_wrist, left_hip, right_hip,
      left_knee, right_knee, left_ankle, right_ankle

    Args:
        results: The results object created in detect_player_keypoints
        save_path: Path to save the output CSV
    '''

    KEYPOINT_NAMES = [
        'nose',
        'left_eye', 'right_eye',
        'left_ear', 'right_ear',
        'left_shoulder', 'right_shoulder',
        'left_elbow', 'right_elbow',
        'left_wrist', 'right_wrist',
        'left_hip', 'right_hip',
        'left_knee', 'right_knee',
        'left_ankle', 'right_ankle',
    ]
    KP_COLS = [f'{kp}_{s}' for kp in KEYPOINT_NAMES for s in ('x', 'y', 'vis')]
    COLS = ['frame'] + KP_COLS

    rows = []
    for frame, result in enumerate(results):
        xy   = result.keypoints.xy.cpu().numpy()[0]    # (17, 2)
        conf = result.keypoints.conf.cpu().numpy()[0]  # (17,)
        flat = np.column_stack([xy, conf]).ravel()     # (51,) — x0,y0,c0,...
        rows.append(np.concatenate([[frame], flat]))

    df = pd.DataFrame(np.array(rows), columns=COLS)
    df['frame'] = df['frame'].astype(int)

    df.to_csv(save_path, index=False)

def detect_player_keypoints(model_path, data_path, save_path, save_frames=False, stream=False):
    ''' Detects the player keypoints and saves them to a csv.

    Args:
        model_path: The path to your trained pose model
        data_path: The path to the data being detectedd

    Returns:
        Returns the results in memory if stream=False. Returns nothing if stream=True
    '''
    model = YOLO(model_path)
    data_name = Path(data_path).stem

    results = model.predict(
        source=data_path,
        save_conf=True,
        project=f'data/{data_name}', 
        save=save_frames,
        save_frames=save_frames,
        stream=stream
    )

    save_results(results, save_path)

    return results

def main():
    test_model_path = 'models/best_player.pt'
    test_vid = '/scratch/network/db0197/LabelingProcess/Squash Data/elias_makin_london2025/rallies/rally6_v2.mp4'

    # saves to predictions/{vid_name}/player_keypoints.csv
    save_path_parents = Path('predictions') / Path(test_vid).stem
    save_path_parents.mkdir(parents=True, exist_ok=True)
    save_path = save_path_parents / 'player_keypoints.csv'

    results = detect_player_keypoints(test_model_path, test_vid, save_path)

    print(type(results))
if __name__ == '__main__':
    main()