from ultralytics import YOLO
from pathlib import Path
import pandas as pd
import numpy as np

def save_results(results, save_path):
    '''
    Saves results object generated by detect_court_keypoints() into a csv with the following headers:
    ['frame', 'front_left_x', 'front_left_y', 'front_left_vis', 'mid_left_x',
       'mid_left_y', 'mid_left_vis', 'mid_right_x', 'mid_right_y',
       'mid_right_vis', 'front_right_x', 'front_right_y', 'front_right_vis',
       'service_right_x', 'service_right_y', 'service_right_vis',
       'service_left_x', 'service_left_y', 'service_left_vis']

    Args:
        results: The results object created in detect_court_keypoints
    '''

    KEYPOINT_NAMES = ['front_left', 'mid_left', 'mid_right', 'front_right', 'service_right', 'service_left']
    KP_COLS = [f'{kp}_{s}' for kp in KEYPOINT_NAMES for s in ('x', 'y', 'vis')]
    COLS = ['frame'] + KP_COLS

    rows = []
    for frame, result in enumerate(results):
        xy   = result.keypoints.xy.cpu().numpy()[0]    # (6, 2)
        conf = result.keypoints.conf.cpu().numpy()[0]  # (6,)
        flat = np.column_stack([xy, conf]).ravel()     # (18,) — x0,y0,c0,x1,y1,c1,...
        rows.append(np.concatenate([[frame], flat]))

    df = pd.DataFrame(np.array(rows), columns=COLS)
    df['frame'] = df['frame'].astype(int)

    df.to_csv(save_path, index=False)

def detect_court_keypoints(model_path, data_path, save_path, save_frames=False, stream=False):
    ''' Detects the court keypoints (front_left, mid_left, mid_right, front_right, service_right, service_left) and saves them to a csv.

    Args:
        model_path: The path to your trained pose model
        data_path: The path to the data being detectedd

    Returns:
        Returns the results in memory if stream=False. Returns nothing if stream=True
    '''
    model = YOLO(model_path)
    data_name = Path(data_path).stem

    results = model.predict(
        source=data_path,
        save_conf=True,
        project=f'data/{data_name}', 
        save=save_frames,
        save_frames=save_frames,
        stream=stream
    )

    save_results(results, save_path)

    return results

def main():
    test_model_path = 'models/best_court.pt'
    test_vid = '/scratch/network/db0197/LabelingProcess/Squash Data/elias_makin_london2025/rallies/rally6_v2.mp4'

    # saves to predictions/{vid_name}/court_keypoints.csv
    save_path_parents = Path('predictions') / Path(test_vid).stem
    save_path_parents.mkdir(parents=True, exist_ok=True)
    save_path = save_path_parents / 'court_keypoints.csv'

    results = detect_court_keypoints(test_model_path, test_vid, save_path)

    print(type(results))
if __name__ == '__main__':
    main()